### PR TITLE
Fix command for fetching tenant_id once more

### PR DESCRIPTION
**Pull request by rhafer**
- remove dangling quote character at the end
- the "-f value -c id" arguments need to come after the subcommand

### CODE REVIEW

**Comment by vuntz** [comment]
Doh; I guess I only tested in the CLI and changed things afterwards :/

+1

**Comment by rhafer** [comment]
> Not a ruby expert, buy IMHO is more clear and less error prone if --os-region "#{node["keystone"]["api"]["region"]}" is replaced with --os-region "#{node[:keystone][:api][:region]}" to avoid quotes inside quotes.

Good point. Updated.

**Comment by rhafer** [comment]
@aplana, better now?

**Comment by rhafer** [comment]
@aplanas, better now?

**Comment by aplanas** [comment]
+1

**Pull request merged**
