### PR TITLE
WIP: Update keystone_register to use the v3 API

### PR DESCRIPTION
**Pull request by rhafer**
This is still imcomplete and needs work. Especially the keystone_register provider needs more changes when it comes to endpoint registration and the tenant -> project renaming. 

BTW, I opted for not trying to make the keystone_register provider compatible with both API versions as that would make it even more complex. So it will always use v3 independent of what is set in the attribute.

### CODE REVIEW

**Comment by dirkmueller** [comment]
+1

**Comment by mjura** [comment]
Please confirm that it was tested and works fine.

Besides this it looks fine to me +1

**Comment by dirkmueller** [comment]
@rhafer testing failed..

**Comment by rsalevsky** [comment]
@rhafer, this repository got merged into [crowbar-openstack](https://github.com/crowbar/crowbar-openstack).
Please open a new pull request there. __Do NOT merge here anymore!__

**Comment by rhafer** [comment]
Closing this old PR. Needs a lot more work anyway and be submitted to crowbar-openstack.

**Pull request closed without merging**
