### PR TITLE
Do not verify the certificate if it is self-signed.

### PR DESCRIPTION
**Pull request by jsuchome**

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by vuntz** [comment]
You need to modify resources/register.rb too

**Comment by vuntz** [comment]
Assuming it works, and after the two commits are squashed, +1

**Comment by jsuchome** [comment]
Works for me, but I'd prefer if someone else could test it as well...

**Comment by rhafer** [comment]
LGTM (didn't test it yet)

BTW, wouldn't it be possible to just default the all the keystone_register parameter to useful values from the ```node``` attributes. E.g. by utilizing KeystoneHelper.keystone_settings in ```resources/register.rb```? AFAIK chef-LWRP have access to the node object. And this would get us rid of a lot of duplicated code in all the openstack recipes. Additionally we wouldn't need to touch all the keystone_register calls again the next time we add parameters.

**Comment by jsuchome** [comment]
@rhafer don't you mean ```providers/register.rb``` ?

**Comment by rhafer** [comment]
> don't you mean providers/register.rb ?

Actually I really meant ```resources/register.rb``` as that's where you can set default values for resources. AFAIK something like:

```
keystone_settings = KeystoneHelper.keystone_settings(node, @cookbook_name)
attribute :protocol, :kind_of => String, :default => keystone_settings['protocol']
```

should be possible in a lightweight resource. I haven't tested this though. And I don't know if is is good style. You might wanna check back with @tboerger  on this.

**Pull request merged**
