### PR TITLE
Backport domain_specific_driver support

### PR DESCRIPTION
**Pull request by rhafer**

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by toabctl** [comment]
+1 (but not tested). Do we have test coverage for that already?

**Comment by rhafer** [comment]
> Do we have test coverage for that already?

No, not yet. I just added a card for that to our backlog.

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
-1, latest changes from master PR need to be re-cherrypicked here

**Comment by rhafer** [comment]
Updated and squashed.

**Comment by vuntz** [comment]
+1

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
